services:
  backend:
    container_name: photo-viewer-backend
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /home/harena/Documents/Project/Archive:/app/data
    depends_on:
      - viewer-db
    ports:
      - "8000:8000"
    entrypoint: ["/entrypoint.sh"]
    # environment:
    #   DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
    networks:
      - viewer_network
  
  vision-redis:
    image: redis:7-alpine
    container_name: vision-redis
    restart: unless-stopped
    ports:
      - "6388:6379"
    networks:
      - viewer_network

  viewer-db:
    image: postgres:16
    restart: always
    container_name: viewer-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - viewer_network
  
  viewer_pgadmin:
    image: dpage/pgadmin4
    container_name: viewer_pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    depends_on:
      - viewer-db
    networks:
      - viewer_network


networks:
  viewer_network:
    external: true

volumes:
  postgres_data:
